name: AutoHop
main: me.desht.autohop.AutoHop
author: desht
website: http://dev.bukkit.org/server-mods/autohop
version: ${project.version}
description: Automatically jump up slopes, one-block-high walls etc.
commands:
  ahop:
    description: Toggle auto-hop enablement
    permission: autohop.hop
    usage: /<command>
permissions:
  autohop.hop:
    description: Allows players to auto-hop
    default: true
